"""progress auth_user

Revision ID: 5998f7e1b8e6
Revises: e9da3ed8e3af
Create Date: 2025-09-14 19:30:59.954926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5998f7e1b8e6'
down_revision: Union[str, Sequence[str], None] = 'e9da3ed8e3af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_users', sa.Column('avatar', sa.String(), nullable=True))
    op.add_column('auth_users', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('auth_users', sa.Column('preferred_language', sa.String(), nullable=True))
    op.add_column('auth_users', sa.Column('timezone', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auth_users', 'timezone')
    op.drop_column('auth_users', 'preferred_language')
    op.drop_column('auth_users', 'is_active')
    op.drop_column('auth_users', 'avatar')
    # ### end Alembic commands ###
