"""add email to user

Revision ID: e9da3ed8e3af
Revises: 010b6c123ba8
Create Date: 2025-09-13 22:50:18.831257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9da3ed8e3af'
down_revision: Union[str, Sequence[str], None] = '010b6c123ba8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_users', sa.Column('email', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'auth_users', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'auth_users', type_='unique')
    op.drop_column('auth_users', 'email')
    # ### end Alembic commands ###
