export enum PaymentErrorCode {
  PAYMENT_ERROR_NONE = 'none',
  PAYMENT_ERROR_INSUFFICIENT_FUNDS = 'insufficient_funds',
  PAYMENT_ERROR_INVALID_CARD = 'invalid_card',
  PAYMENT_ERROR_CARD_EXPIRED = 'invalid_card_expired',
  PAYMENT_ERROR_CARD_DECLINED = 'invalid_card_declined',
  PAYMENT_ERROR_NETWORK_ERROR = 'network_error',
  PAYMENT_ERROR_FRAUD_DETECTED = 'insufficient_funds',
  PAYMENT_ERROR_LIMIT_EXCEEDED = 'limit_exceeded',
  PAYMENT_ERROR_INVALID_CVV = 'invalid_cvv',
  PAYMENT_ERROR_PROCESSING_ERROR = 'internal_error',
  PAYMENT_ERROR_TIMEOUT = 'internal_timeout',
  PAYMENT_ERROR_DUPLICATE_TRANSACTION = 'duplicate_transaction',
  PAYMENT_ERROR_INVALID_AMOUNT = 'invalid_amount',
  PAYMENT_ERROR_CURRENCY_NOT_SUPPORTED = 'invalid_currency_not_supported',
  PAYMENT_ERROR_PAYMENT_METHOD_NOT_SUPPORTED = 'invalid_payment_method_not_supported',
  PAYMENT_ERROR_REQUIRES_3DS = 'requires_3ds',
}
