"""fix category model

Revision ID: 782d1b6d7314
Revises: 16a50113706b
Create Date: 2025-09-02 03:35:32.970074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '782d1b6d7314'
down_revision: Union[str, None] = '16a50113706b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_inventory_id'), 'inventory', ['id'])
    op.create_unique_constraint(op.f('uq_product_categories_id'), 'product_categories', ['id'])
    op.create_unique_constraint(op.f('uq_product_images_id'), 'product_images', ['id'])
    op.create_unique_constraint(op.f('uq_product_tags_id'), 'product_tags', ['id'])
    op.create_unique_constraint(op.f('uq_products_id'), 'products', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_products_id'), 'products', type_='unique')
    op.drop_constraint(op.f('uq_product_tags_id'), 'product_tags', type_='unique')
    op.drop_constraint(op.f('uq_product_images_id'), 'product_images', type_='unique')
    op.drop_constraint(op.f('uq_product_categories_id'), 'product_categories', type_='unique')
    op.drop_constraint(op.f('uq_inventory_id'), 'inventory', type_='unique')
    # ### end Alembic commands ###
