"""add parent_id to category model

Revision ID: 8937367ba9a2
Revises: 782d1b6d7314
Create Date: 2025-09-02 11:57:01.511196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8937367ba9a2'
down_revision: Union[str, None] = '782d1b6d7314'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_categories', sa.Column('parent_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_product_categories_parent_id'), 'product_categories', ['parent_id'], unique=False)
    op.create_foreign_key(op.f('fk_product_categories_parent_id_product_categories'), 'product_categories', 'product_categories', ['parent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_product_categories_parent_id_product_categories'), 'product_categories', type_='foreignkey')
    op.drop_index(op.f('ix_product_categories_parent_id'), table_name='product_categories')
    op.drop_column('product_categories', 'parent_id')
    # ### end Alembic commands ###
