"""add ProductReservation

Revision ID: a398544b0352
Revises: d4a1f8d3f4c9
Create Date: 2025-09-25 00:47:12.259106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a398544b0352'
down_revision: Union[str, None] = 'd4a1f8d3f4c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_reservations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('reservation_id', sa.String(length=255), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('reserved_by_user_id', sa.UUID(), nullable=True),
    sa.Column('reserved_by_service', sa.String(length=100), nullable=True),
    sa.Column('reservation_reason', sa.String(length=50), nullable=False),
    sa.Column('reference_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_product_reservations_product_id_products'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_reservations')),
    sa.UniqueConstraint('id', name=op.f('uq_product_reservations_id'))
    )
    op.create_index('idx_product_status', 'product_reservations', ['product_id', 'status'], unique=False)
    op.create_index('idx_reservation_product', 'product_reservations', ['reservation_id', 'product_id'], unique=False)
    op.create_index('idx_reservation_status', 'product_reservations', ['reservation_id', 'status'], unique=False)
    op.create_index(op.f('ix_product_reservations_product_id'), 'product_reservations', ['product_id'], unique=False)
    op.create_index(op.f('ix_product_reservations_reference_id'), 'product_reservations', ['reference_id'], unique=False)
    op.create_index(op.f('ix_product_reservations_reservation_id'), 'product_reservations', ['reservation_id'], unique=False)
    op.create_index(op.f('ix_product_reservations_reserved_by_user_id'), 'product_reservations', ['reserved_by_user_id'], unique=False)
    op.create_index(op.f('ix_product_reservations_status'), 'product_reservations', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_reservations_status'), table_name='product_reservations')
    op.drop_index(op.f('ix_product_reservations_reserved_by_user_id'), table_name='product_reservations')
    op.drop_index(op.f('ix_product_reservations_reservation_id'), table_name='product_reservations')
    op.drop_index(op.f('ix_product_reservations_reference_id'), table_name='product_reservations')
    op.drop_index(op.f('ix_product_reservations_product_id'), table_name='product_reservations')
    op.drop_index('idx_reservation_status', table_name='product_reservations')
    op.drop_index('idx_reservation_product', table_name='product_reservations')
    op.drop_index('idx_product_status', table_name='product_reservations')
    op.drop_table('product_reservations')
    # ### end Alembic commands ###
